// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl4F6yl92hNyVnS62O_29otl0eTi46YjY',
    appId: '1:430310469454:web:ef02f58eb1c08cfc19b81f',
    messagingSenderId: '430310469454',
    projectId: 'pharmacymodule-826cc',
    authDomain: 'pharmacymodule-826cc.firebaseapp.com',
    storageBucket: 'pharmacymodule-826cc.appspot.com',
    measurementId: 'G-XXLSNH7K62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-BQ69eypMnNe-Ukk6cSvavE5vx8suphc',
    appId: '1:430310469454:android:c7732ba6cf8ef04c19b81f',
    messagingSenderId: '430310469454',
    projectId: 'pharmacymodule-826cc',
    storageBucket: 'pharmacymodule-826cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIwDa9riTj8L-NbDT1pQ0nSKHMRITcSsw',
    appId: '1:430310469454:ios:9490a19565bbfe2119b81f',
    messagingSenderId: '430310469454',
    projectId: 'pharmacymodule-826cc',
    storageBucket: 'pharmacymodule-826cc.appspot.com',
    iosClientId: '430310469454-1vggkdcc7qojkrcit6n85uqt7778pj5i.apps.googleusercontent.com',
    iosBundleId: 'com.example.pharmacy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIwDa9riTj8L-NbDT1pQ0nSKHMRITcSsw',
    appId: '1:430310469454:ios:9490a19565bbfe2119b81f',
    messagingSenderId: '430310469454',
    projectId: 'pharmacymodule-826cc',
    storageBucket: 'pharmacymodule-826cc.appspot.com',
    iosClientId: '430310469454-1vggkdcc7qojkrcit6n85uqt7778pj5i.apps.googleusercontent.com',
    iosBundleId: 'com.example.pharmacy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDl4F6yl92hNyVnS62O_29otl0eTi46YjY',
    appId: '1:430310469454:web:b14f4b976e176e1a19b81f',
    messagingSenderId: '430310469454',
    projectId: 'pharmacymodule-826cc',
    authDomain: 'pharmacymodule-826cc.firebaseapp.com',
    storageBucket: 'pharmacymodule-826cc.appspot.com',
    measurementId: 'G-FF6Y6GCV53',
  );
}
